name: build-arm64-gpsp

on:
  workflow_dispatch:

jobs:
  arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install aarch64 toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build gpSP core (arm64)
        run: |
          export CC=aarch64-linux-gnu-gcc
          make platform=arm64 -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpsp_core_arm64
          path: gpsp_libretro.so
